// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

const errorMessage = (error: unknown) => {
  if (!error) return "";
  if (error instanceof Error) return error.message;
  if (typeof error === "object" && "message" in error) {
    return String((error as { message?: unknown }).message ?? error);
  }
  return String(error);
};

const isUnsupportedManagedProvider = (error: unknown) =>
  /provider ['"]?(google|apple)['"]? is not supported|provider.*not supported/i.test(errorMessage(error));

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error && !isUnsupportedManagedProvider(result.error)) {
        return result;
      }

      if (result.error && isUnsupportedManagedProvider(result.error)) {
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider,
          options: {
            redirectTo: opts?.redirect_uri,
            queryParams: opts?.extraParams,
            skipBrowserRedirect: false,
          },
        });

        if (error) return { error };
        if (data?.url) {
          window.location.assign(data.url);
          return { redirected: true };
        }
        return { error: new Error("OAuth redirect URL was not returned") };
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
